### PR TITLE
added test account 0x279e112d0D182A7234Fe11D0363B3C6f2edd71e4 to list…

### PR DESCRIPTION
**Pull request by Simon-Pokorny**
Hi,

I've added my address to the purgatory list, because I want to use that address for testing on my personal market fork and I dont want to flood the official market with all the data assets that I'm going to create. 

Thank you

Simon

### CODE REVIEW

**Review by trentmc — APPROVED** [review]

**Comment by LoznianuAnamaria** [comment]
Hi @Simon-Pokorny! As your PR is coming from an external fork, the checks cannot run. Can you please create the PR directly in a branch in the list-purgatory repo? thank you 🙏

**Comment by Simon-Pokorny** [comment]
Ah thank you for the hint! that is good to know. 
I'm going to create a new pull request and close this one.

**Comment by Simon-Pokorny** [comment]
@AnaLoznianu can you help me to get the access rights to push to this repository? 
The [contributing guidelines](https://docs.oceanprotocol.com/building-with-ocean/contributing#workflow) describe the workflow to contribute changes via a fork. Is this repository organized differently?

**Comment by LoznianuAnamaria** [comment]
You are right @Simon-Pokorny 😄 we are specifying to use a fork
I'll reopen and merge this PR

**Comment by Simon-Pokorny** [comment]
Thanks a lot! :)

**Pull request merged**
