### PR TITLE
Request to remove retired datasets from the Ocean Marketplace

### PR DESCRIPTION
**Pull request by realdatawhale**
Fixes # .

We are looking to retire the following datasets. We have already announced the retirement of the pool assets on our official Twitter account.

STUTUR-23
https://market.oceanprotocol.com/asset/did:op:312d24dE83610e351A1977EbA8851CeA8D020e1B

MARRAY-61
https://market.oceanprotocol.com/asset/did:op:7c0D0DC5bCACeDf8121047c34bFb0ABeB00d4b19

FIXED PRICE: SALOTT-11
https://market.oceanprotocol.com/asset/did:op:8b4045F37dB438F9761c615e9512c3Bf742e29cf

FIXED PRICE: EGRFIS-84
https://market.oceanprotocol.com/asset/did:op:0e36Caa04EbefC1B2A77620F41e6c343a1d9d660

### CODE REVIEW

**Review by jamiehewitt15 — CHANGES_REQUESTED** [review]
@realdatawhale can you edit the `lists-assets.json` so that you add the did's to the purgatory list along with the reason.

There is an example of how it is done in a previous pull request 
 here: https://github.com/oceanprotocol/list-purgatory/pull/47/files

**Comment by realdatawhale** [comment]
@jamiehewitt15 , I've tried to do this on my own but couldn't edit it. Not working with GitHub myself, so everything is very new here! My apologies. Hope this helps, so you can copy it in:

"did": "did:op:312d24dE83610e351A1977EbA8851CeA8D020e1B",
        "reason": "isRetired"

"did": "did:op:7c0D0DC5bCACeDf8121047c34bFb0ABeB00d4b19",
        "reason": "isRetired"

"did": "did:op:8b4045F37dB438F9761c615e9512c3Bf742e29cf",
        "reason": "isRetired"

"did": "did:op:0e36Caa04EbefC1B2A77620F41e6c343a1d9d660",
        "reason": "isRetired"

**Comment by jamiehewitt15** [comment]
@realdatawhale I have added them to the purgatory list. 

@kremalicious can you review?

**Comment by kremalicious** [comment]
all good so far, just the reason could be more user friendly as it's showing up over in market in UI. We do not have anything for this case standardized in here, but would suggest `"reason": "retired by publisher"`

**Comment by kaimeinke** [comment]
I agree, the "retired" functionality seems like a "must have" to me and it should be different than the classic purgatory request. I should be limited to the specific asset.

**Comment by realdatawhale** [comment]
> all good so far, just the reason could be more user friendly as it's showing up over in market in UI. We do not have anything for this case standardized in here, but would suggest `"reason": "retired by publisher"`

I agree: "Retired By Publisher" would be great.

I still see them on the UI at the moment, not sure by when they'll be removed. Thanks for your help all!

**Comment by jamiehewitt15** [comment]
> I still see them on the UI at the moment, not sure by when they'll be removed. Thanks for your help all!

@realdatawhale they will be removed when this PR is merged

**Comment by jamiehewitt15** [comment]
@kaimeinke we have [an issue](https://github.com/oceanprotocol/market/issues/754) for it but it is currently low priority so we will continue using purgatory to retire assets for now.

**Review by kremalicious — DISMISSED** [review]

**Review by jamiehewitt15 — DISMISSED** [review]

**Comment by jamiehewitt15** [comment]
This requires a code owner review @daneklustig @innoprenuer @sheriff4 @brucepon

**Review by daneklustig — APPROVED** [review]

**Pull request merged**
