### PR TITLE
Updated list-assets.json

### PR DESCRIPTION
**Pull request by jarrillaga**
Fixes # .

Changes proposed in this PR:

- We added new datatokens that should be sent to the purgatory.

### CODE REVIEW

**Comment by jarrillaga** [comment]
Please accept this PR in order to add these datatokens to the purgatory.

**Comment by trentmc** [comment]
Thanks for flagging.

There needs to be more transparency. For each of these, please be more specific. E.g. is it a trademark violation, sensitive data, etc? See the list "How Does A Data Asset Enter Purgatory?" [here](https://github.com/oceanprotocol/list-purgatory/blob/main/policies/README.md).

Also, currently there only data assets are flagged. Typically, when an asset is flagged, the _actor_ should also be flagged and put into purgatory too. (Details in [purgatory README](https://github.com/oceanprotocol/list-purgatory/blob/main/policies/README.md).) Please do this.

cc @mihaisc @alexcos20

**Comment by kremalicious** [comment]
what's the status of this?

**Comment by LoznianuAnamaria** [comment]
@jarrillaga Thanks for opening this PR! Can you please update it with the suggestions Trent gave? 
Thanks!

**Comment by LoznianuAnamaria** [comment]
I am closing this as it's hanging for a long time with no reply from the owner. 
@jarrillaga Please open another PR with more details if you still want to add the DIDs to purgatory. Thank you!

**Pull request closed without merging**
