### PR TITLE
Ban 0x801e12B93A570930cB68aC29F3450BC5AFD78350

### PR DESCRIPTION
**Pull request by TimDaub**
For copyright infringement, see thread here: https://port.oceanprotocol.com/t/integration-of-openmined-and-zero-knowledge-proofs-into-ocean-protocol/522

### CODE REVIEW

**Comment by kaimeinke** [comment]
I agree. This is not how we like to play. Looking forward to the answer in the DAO forum (port). Thank you @TimDaub for keeping your eyes open!

**Comment by w1kke** [comment]
Wouldn't it be more helpful to resolve the conflict instead of directly banning the person?
I know that Gary and Sheridan have been in talks about this project earlier.
The proposal of course has to be corrected.

**Comment by TimDaub** [comment]
> Wouldn't it be more helpful to resolve the conflict instead of directly banning the person?

Can you be honest by copying several paragraphs of a scientific paper without quoting the author and by retrospectively claiming that e.g. you forgot to put references? I don't think so. Additionally, it is an identical copy, not even paraphrasing. The infringing author must have put in dedicated work towards finding the original author's TeX file or by manually copying the paragraph. How can this happen "unintentionally?"

 In my view "Ignorance is no excuse in law.". And I don't see how someone can be trusted with receiving OceanDAO grants money for implementing something as complex as zkrollups when having shown signs of dishonesty beforehand.

> The proposal of course has to be corrected.

No. The proposal clearly has to be disqualified.

**Comment by kaimeinke** [comment]
It is clear that the proposal has to be corrected and it is good that it will be done or has been done by now. For me personally I would not like to vote for it after what happened, but I would prefer to let the community decide about this. I don't want to be a judge on this topic so I would let the voters decide about it and not ban it outright. Maybe I am wrong about this, but in doubt ... and I am in doubt ... I will not vote for a ban.

**Comment by anapheys** [comment]
https://port.oceanprotocol.com/t/integration-of-openmined-and-zero-knowledge-proofs-into-ocean-protocol/522/10?u=alexn

**Comment by anapheys** [comment]
For OceanDAO project proposals that do not meet the [OceanDAO criteria](https://github.com/oceanprotocol/oceandao/wiki/project-criteria) it is the practice to not include them in the OceanDAO voting ballot. 

"Purgatory" traditionally has been established for bad actors on the Ocean Marketplace. At this junction, this proposal will not be included in OceanDAO Round Four AND my recommendation is to NOT add their address to purgatory as this is not Ocean Market. 

Thank you for everyone's commitment to OceanDAO integrity!


With regard this OceanDAO Project Proposal:

https://port.oceanprotocol.com/t/integration-of-openmined-and-zero-knowledge-proofs-into-ocean-protocol/522/10?u=alexn

"Unfortunately, as the proposal deadline approaches, we are unable to verify the legitimacy of the author and the proposal is without proper open source citations. Therefore, this proposal will NOT be induced in OceanDAO Round Four.

Chaindev is welcome to make updates to their proposal for future OceanDAO Rounds (eg Round Five) if they can address the above concerns.

Thank you to the community for added integrity to OceanDAO."

**Review by daneklustig — APPROVED** [review]

**Pull request merged**
