### PR TITLE
Update list-accounts.json

### PR DESCRIPTION
**Pull request by w1kke**
Rugpull on these datasets:
https://market.oceanprotocol.com/asset/did:op:0f5B491ff05f5720F2cF7E5eD8ad73Af779Caf4C
https://market.oceanprotocol.com/asset/did:op:0A932F55aE55C26c22c0247Eef5D19c3ff809292
This is the corresponding Twitter account:
https://twitter.com/pvlace808mafia

### CODE REVIEW

**Comment by brucepon** [comment]
Before merging, is there a "rule" that obligates a data provider to also provide liquidity? 
The expectation of a data provider to do so is more of a community norm than a hard requirement. 

If a publisher wishes to pull out all their liquidity, how does one assess it to be malicious and worthy of purgatory?
Some factors: 
1. Time - if liquidity is yanked 1 day after publishing vs 2 weeks. Can the 2 week period be considered "normal business operations"
2. Profit - publisher stands to make a lot of money off the community vs relatively smaller profits
3. Transparency - no prior notice vs communicated
4. Harm - few LPs getting hurt vs a lot of LPs taking steep losses
5. Experience - publisher is new and inexperienced vs active in the Ocean community and Telegram groups.
6. Malicious Intent - clear pump and dump and rug pull 

In a previous instance, the publisher withdrew liquidity within 24h (short Time), took 10x profits, had no transparency to the community, harmed many community members and shook trust, was inexperienced but did hype up their data set significantly prior to launch - hence purgatory.

In this case, the publisher kept liquidity in for an extended period of time, took some profits, didn't communicate, harmed a more limited set of LPs, was quite experienced and active in the community and malicious intent is not discernable.

Would be great to get more opinions on this from the community and team.

**Comment by w1kke** [comment]
I think that taking the liquidity out of a pool without any announcement should be treated as a malicious act. This pool creator used Twitter to verify the dataset but then just took out all their liquidity without announcement. That should not go without an outcry of the community.

Whatever time period they kept their liquidity in, communicating openly to the liquidity providers is a must in my opinion.
I also don't see the pool creator as being entitled to remove their liquidity whenever they want. They were building a pool not only with their funds but others.
And here the trust was violated which demands action from my point of view.

I would never invest anymore in this person's pools and would warn others to refrain from doing that.

**Comment by kaimeinke** [comment]
I fully agree with the assessments above. I did DM the content provider, was in chat with him before that when I supported him to update and care about his sets and now he is plain silent and does not want to talk about the act itself, the actions that led to this point and about the future. The ill intent is now very much confirmed after a reasonable amount of time. 
Ten hours and community outcry on various channels should be enough for him to explain himself.
image

**Review by brucepon — DISMISSED** [review]

**Comment by brucepon** [comment]
Ok. Approved

**Review by sheriff4 — DISMISSED** [review]

**Comment by kremalicious** [comment]
solved the merge conflict, please re-review and merge

**Pull request merged**
