### PR TITLE
temporarily remove STRDOL-44

### PR DESCRIPTION
**Pull request by TimDaub**
Details: https://github.com/oceanprotocol/aquarius/issues/419#issuecomment-816758567

### CODE REVIEW

**Review by innopreneur — COMMENTED** [review]
@TimDaub  Price feeds also affects many other DT prices (other than STRDOL-44). And adding just this one here wouldn't be the best solution. Also purgatory list serves special purpose and all added datasets suffers consequences. So, best way to treat this situation (while devs fix price feeds) is -  "to put a flag/banner on rugpullindex and other Dapps that uses this price feed with a link to the issue in Aquarius repo"

**Comment by TimDaub** [comment]
> So, best way to treat this situation (while devs fix price feeds) is - "to put a flag/banner on rugpullindex and other Dapps that uses this price feed with a link to the issue in Aquarius repo"

I'm aware that the proposed changeset here is the worst possible fix. I still proposed it as my [original post](https://github.com/oceanprotocol/aquarius/issues/419) was filed 24 days ago for a bug that is non-acceptable in production. My intention was to propose it as a fix that can resolve the issue within one second, instead of waiting a few more days for progress updates...

Since you ask to put a flag, may I ask you what's the timeline for fixing the problem?

**Comment by innopreneur** [comment]
> > So, best way to treat this situation (while devs fix price feeds) is - "to put a flag/banner on rugpullindex and other Dapps that uses this price feed with a link to the issue in Aquarius repo"
> 
> I'm aware that the proposed changeset here is the worst possible fix. I still proposed it as my [original post](https://github.com/oceanprotocol/aquarius/issues/419) was filed 24 days ago for a bug that is non-acceptable in production. My intention was to propose it as a fix that can resolve the issue within one second, instead of waiting a few more days for progress updates...
> 
> Since you ask to put a flag, may I ask you what's the timeline for fixing the problem?

@DMats is mostly working on the fix. He is the best person to answer this. But lets take this conversation back to the main thread (of the bug). If that's okay let's close this thread.

**Comment by MantisClone** [comment]
The original issue [aquarius #419](https://github.com/oceanprotocol/aquarius/issues/419) was closed and marked wontfix. Recommend closing this issue as well.

**Pull request closed without merging**
